# Cargo.toml

[package]
name = "pngspy"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pngspy"
path = "src/bin/main.rs"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
reqwest = { version = "0.12.12", features = ["blocking"] }
tempfile = "3.18.0"